var rp4 = [1, "bharat"];
var rishi5;
rishi5 = [1, "bharat", true, 20, "hii"];
console.log(rp4[1]);
console.log(rishi5[2]);
rp4.push("sohil");
rishi5.push(false);
console.log(rp4[2]);
rishi5[1] = rishi5[1].concat("welcome");
console.log(rishi5);
